fixtures:
  repositories:
    'apache': 'git://github.com/kickstandproject/kickstandproject-apache.git'
    'common': 'git://github.com/kickstandproject/kickstandproject-common.git'
    'stdlib': 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
  symlinks:
    'puppet': '#{source_dir}'
